Tuck_shop/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
]

myapp/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('login/',views.login_view,name="login"),
    path('home/',views.home_view,name="home"),
    path('student/', views.students, name='student'),
    path('add-student/', views.add_student, name='add_student'),
    path('purchase/', views.purchase, name='purchase'),
    # path('purchase/add/', views.add_purchase, name='add_purchase'),
    path('inventory/', views.inventory, name='inventory'),
    path('inventory/add/', views.add_inventory, name='add_inventory'),
    path('inventory/update/<int:id>/', views.update_inventory, name='update_inventory'),
    path('inventory/delete/<int:id>/', views.delete_inventory, name='delete_inventory'),
    path('student/update/<int:id>/', views.update_student, name='update_student'),
    path('student/delete/<int:id>/', views.delete_student, name='delete_student'),
    path('purchase/delete/<int:id>/', views.delete_purchase, name='delete_purchase'),
    # path('save_purchase/', views.save_purchase, name='save_purchase'),
    path('graph/', views.graph_view, name='graph'),
    path('student_graph/', views.student_graph_view, name='student_graph'),
    # path('add_purchase/', views.add_purchase, name='add_purchase'),
    path('download_excel_sheet/', views.download_excel_sheet, name='download_excel_sheet'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('view_cart/', views.view_cart, name='view_cart'),
    path('buy_item/', views.buy_items, name='buy_item'),



]

myapp/models.py
from django.db import models

# Models go here


class Student(models.Model):
    name = models.CharField(max_length=100)
    grade = models.CharField(max_length=20)
    mail = models.EmailField()
    limit = models.IntegerField()

    def __str__(self):
        return self.name

 
class Inventory(models.Model):
    item_name = models.CharField(max_length=100)
    last_restock = models.DateField()
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    availability = models.BooleanField(default=False)

    def __str__(self):
        return self.item_name

    
class Purchase(models.Model):
    student_name = models.ForeignKey(Student, on_delete=models.CASCADE)
    item =  models.ForeignKey(Inventory,on_delete=models.CASCADE,default=False)
    purchase_date = models.DateField()
    total_price = models.IntegerField(null=True)
    purchased_quantity = models.IntegerField(default=False)

    def __str__(self):
        return f"Purchase by {self.student_name}"

myapp/forms.py
from django import forms
from .models import Student,Inventory,Purchase

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name', 'grade', 'mail', 'limit']

class PurchaseForm(forms.ModelForm):
    purchase_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    class Meta:
        model = Purchase
        fields = ['student_name', 'item','purchase_date','purchased_quantity']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Query the database to get the choices for the dropdowns
        self.fields['student_name'].queryset = Student.objects.all()
        self.fields['item'].queryset = Inventory.objects.all()

class InventoryForm(forms.ModelForm):
    last_restock = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = Inventory
        fields = ['item_name', 'last_restock', 'quantity', 'price', ]
        widgets = {
            'availabity': forms.CheckboxInput(),
        }

myapp/views.py
from django.forms import modelformset_factory
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
from django.contrib.auth.decorators import login_required
from .forms import StudentForm
from .models import Student,Purchase,Inventory
from .forms import PurchaseForm,InventoryForm ,StudentForm 
from django.db.models import Q
from django.db.models import Sum
from datetime import datetime
from collections import Counter
import pandas as pd
from django.http import HttpResponse
import io 
from xlsxwriter.workbook import Workbook
from django.core.exceptions import ObjectDoesNotExist



def download_excel_sheet(request):
    month = request.GET.get('month')
    year = request.GET.get('year')
    if month and year:
        purchases = Purchase.objects.filter(purchase_date__year=year, purchase_date__month=month)
    else:
        purchases = Purchase.objects.all()
    
    # Aggregate the data by student_name and calculate the total amount for each student
    student_data = purchases.values('student_name__name', 'student_name__id', 'student_name__mail').annotate(total_amount=Sum('total_price'))
    
    # Create a DataFrame from the aggregated data
    df = pd.DataFrame(student_data)
    
    # Prepare the buffer to hold the Excel file
    buffer = io.BytesIO()
    writer = pd.ExcelWriter(buffer, engine='xlsxwriter')
    
    # Write the DataFrame to the Excel file
    df.to_excel(writer, index=False)
    writer.close()
    buffer.seek(0)
    
    # Set the appropriate response headers for downloading the Excel file
    response = HttpResponse(buffer, content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename=student_data.xlsx'
    
    return response

# def add_purchase(request):
#     inventory_items = Inventory.objects.all()
#     purchases = Purchase.objects.all()
#     total_price = 0
#     error_message = ""

#     if request.method == 'POST':
#         form = PurchaseForm(request.POST)
#         if form.is_valid():
#             student_name = form.cleaned_data['student_name']
#             item = form.cleaned_data['item']
#             purchased_quantity = form.cleaned_data['purchased_quantity']
#             item_price = item.price  # Use the item price from the selected item
#             purchase_date = form.cleaned_data['purchase_date']
#             try:
#                 student = Student.objects.get(name=student_name)
#                 limit = student.limit
#             except Student.DoesNotExist:
#                 limit_rate = 0  # Set a default value for the limit rate if the student is not found

#             if item.availability and item.quantity >= purchased_quantity and purchased_quantity > 0:
#                 total_price = item_price * purchased_quantity

#                 item.quantity -= purchased_quantity
#                 item.save()
#                 if item_price > limit:
#                     error_message = "The selected item's price exceeds the limit rate. You cannot purchase this item."

#                 # Save carted item to Purchase table
#                 purchase = Purchase(
#                     student_name=student_name,
#                     item=item,
#                     purchased_quantity=purchased_quantity,
#                     total_price=total_price,
#                     purchase_date=purchase_date
#                 )
#                 purchase.save()

#                 # Clear the form for adding the next item
#                 form = PurchaseForm()

#             else:
#                 if not item.availability:
#                     error_message = "The selected item is not available in the inventory."
#                 elif item.quantity < purchased_quantity or purchased_quantity <= 0:
#                     error_message = "The quantity is invalid or exceeds the available quantity."

#         else:
#             error_message = "The form is not valid. Please check the input fields."

#     else:
#         form = PurchaseForm()

#     return render(request, 'add_purchase.html', {'inventory_items': inventory_items, 'purchases': purchases, 'form': form, 'total_price': total_price, 'error_message': error_message})


def add_to_cart(request):
    inventory_items = Inventory.objects.all()
    purchases = Purchase.objects.all()
    total_price = 0
    error_message = ""

    if request.method == 'POST':
        form = PurchaseForm(request.POST)
        if form.is_valid():
            student_name = form.cleaned_data['student_name']
            item = form.cleaned_data['item']
            purchased_quantity = form.cleaned_data['purchased_quantity']
            item_price = item.price  # Use the item price from the selected item
            purchase_date = form.cleaned_data['purchase_date']
            try:
                student = Student.objects.get(name=student_name)
                limit = student.limit
            except Student.DoesNotExist:
                limit = 0  # Set a default value for the limit rate if the student is not found

            if item.availability and item.quantity >= purchased_quantity and purchased_quantity > 0:
                total_price = item_price * purchased_quantity

                item.quantity -= purchased_quantity
                item.save()

            if item_price > limit:
                error_message = "The selected item's price exceeds the limit rate. You cannot purchase this item."

                # Save carted item to Purchase table
                purchase = Purchase(
                    student_name=student_name,
                    item=item,
                    purchased_quantity=purchased_quantity,
                    total_price=total_price,
                    purchase_date=purchase_date
                )
                purchase.save()

                # Clear the form for adding the next item
                form = PurchaseForm()

            else:
                if not item.availability:
                    error_message = "The selected item is not available in the inventory."
                elif item.quantity < purchased_quantity or purchased_quantity <= 0:
                    error_message = "The quantity is invalid or exceeds the available quantity."

        else:
            error_message = "The form is not valid. Please check the input fields."

    else:
        form = PurchaseForm()

    return render(request, 'add_to_cart.html', {'inventory_items': inventory_items, 'purchases': purchases, 'form': form, 'total_price': total_price, 'error_message': error_message})

# def view_cart(request):
#     cart_items = Purchase.objects.all()
#     total_cart_price = sum(item.total_price for item in cart_items)
#     return render(request, 'view_cart.html', {'cart_items': cart_items, 'total_cart_price': total_cart_price})

def view_cart(request):
    cart = request.session.get('cart', {})
    cart_items = []
    total_cart_price = 0

    for cart_item in cart.values():
        item = Inventory.objects.get(id=cart_item['item_id'])
        total_cart_price += cart_item['total_price']
        cart_items.append({
            'item': item,
            'purchased_quantity': cart_item['purchased_quantity'],
            'total_price': cart_item['total_price'],
            'purchase_date': cart_item['purchase_date'],
        })

    return render(request, 'view_cart.html', {'cart_items': cart_items, 'total_cart_price': total_cart_price})

def buy_items(request):
    cart = request.session.get('cart', {})
    for cart_item in cart.values():
        try:
            student_name = cart_item['student_name']
            item_id = cart_item['item_id']
            purchased_quantity = cart_item['purchased_quantity']
            total_price = cart_item['total_price']
            purchase_date = cart_item['purchase_date']

            item = Inventory.objects.get(id=item_id)
            student = Student.objects.get(name=student_name)
            limit = student.limit

            if item.availability and item.quantity >= purchased_quantity and purchased_quantity > 0:
                # Save carted item to Purchase table
                purchase = Purchase(
                    student_name=student_name,
                    item=item,
                    purchased_quantity=purchased_quantity,
                    total_price=total_price,
                    purchase_date=purchase_date
                )
                purchase.save()

                # Update inventory quantity
                item.quantity -= purchased_quantity
                item.save()

        except (ObjectDoesNotExist, KeyError):
            # Handle the case when the item or student does not exist, or the cart item is missing some keys
            return redirect('purchase')

    # Clear the cart after buying items
    request.session['cart'] = {}

    return redirect('purchase')



@login_required
def home_view(request):
    return render(request, 'home.html')

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request,username=username, password=password)
        if user is not None:
            login(request,user)
            return redirect('home')
        else:
            error_message = "invalid username or password"
            return render(request,'login.html',{'error_message':error_message})
    else:
        return render(request,'login.html')

def students(request):
    search_query = request.GET.get('search_query', '')
    students = Student.objects.all()

    if search_query:
        students = Student.objects.filter(name__icontains=search_query)

    context = {
        'students': students,
    }
    return render(request, 'students.html', context)

def add_student(request):
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():

myapp/templates/add_inventory.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Add Inventory</title>
   
</head>
<body>
    <form method="post" action="{% url 'add_inventory' %}">
        {% csrf_token %}
        <h1>Add New Item</h1>
        {{form.as_p}}
        <div  class="back-btn">
         <button onclick="location.href='{% url 'inventory' %}'">Back</button>
        <input type="submit" value="Add Item">
        </div>

    </form>
     <style>
        .back-btn button {
            padding: 10px 14px;
            background-color: #8AC5C5;
            color: black;
            border: none;
            border-radius: 12px;
            cursor: pointer;
        }
        body {
            font-family: Arial, sans-serif;
            background-color: #f1f1f1;
            padding: 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
            background-color: #E87461;
        }
        h1 {
            text-align: center;
            margin-bottom: 20px;
            color: #FE910A;
        }
        form {
            width: 350px;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            background-color: #E0C879;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
        }
        label {
            display: block;
            margin-bottom: 8px;
        }
        input[type="text"],
        input[type="number"],
        input[type="date"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 12px;
            border-radius: 4px;
            border: 1px solid #ccc;
            box-sizing: border-box;
        }

        input[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 10px 16px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
        }

        input[type="submit"]:hover {
            background-color: #45a049;
        }

        .back-btn {
            display: flex;
            justify-content: space-between;
            margin-top: 20px;
        }
        
        .back-btn button {
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
            width: 80px;
        }

        
        .back-btn button:hover {
          background-color: #45a049;  
        }
        
    </style>
</head>
</html>

myapp/templates/add_purchase.html
{%  load static %}



 <!DOCTYPE html>
<html>
<head>
    <title>Add Purchase</title>
</head>

<body>
</head>
<body>
 


<form method="post" id="addToCartForm">
    <h1>Add Purchase</h1>
    {% csrf_token %}
    {{ form.as_p }}
   
    <div  class="back-btn">
     <button  onclick="location.href='{% url 'purchase' %}'"> Back
     </button>
      <button type="submit" name="action" value="add_to_cart">Buy Items</button>
    </div>
   <div class="alert-box" id="popupMessage">
    <p>  {{ error_message }} </p>
</div> 
</form>


<div id="totalAmountDisplay">
    {% if total_price %}
        <p>Total Price: {{ total_price }}</p>
        <script>
            setTimeout(function() {
                window.location.href = "{% url 'purchase' %}";
            }, 2000); // Redirect after 3 seconds (adjust the delay as needed)
        </script>
    {% endif %}
</div>
<script>
    const quantityInput = document.getElementById('id_purchased_quantity');
    const itemSelect = document.getElementById('id_item'); // Assuming the HTML id for the item select field is "id_item"
    const totalAmountDisplay = document.getElementById('totalAmountDisplay');

    function calculateTotalAmount() {
        const quantity = parseInt(quantityInput.value);
        const itemPrice = parseFloat(itemSelect.options[itemSelect.selectedIndex].getAttribute('data-price'));
        const totalAmount = isNaN(quantity) || isNaN(itemPrice) ? '' : (quantity * itemPrice).toFixed(2);
        totalAmountDisplay.innerHTML = totalAmount ? `<p>Total Price: ${totalAmount}</p>` : '';

    if (parseInt(quantity) <= 0 || parseFloat(lastPurchaseAmount) <= 0) {
        document.getElementById('error-message').innerText = 'Invalid quantity or last purchase amount.';
        document.getElementById('error-message').style.display = 'block';
    } else {
        document.getElementById('error-message').innerText = '';
        document.getElementById('error-message').style.display = 'none';

    }
}
function showAlert() {
    var popup = document.getElementById("popupMessage");
    popup.style.display = "block";
    var duration = 3000; // 5 seconds (adjust this value as needed)

    setTimeout(function() {
        popup.style.display = "none";
    }, duration);
}
window.onload = function() {
    var error_message = "{{ error_message }}";
    if (error_message) {
        showAlert();
    }
};
</script>

 
</body>
</html> 

 
<style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            background-color: #f1f1f1;
            padding: 20px;
            background-color: #E87461;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
            color: #FE910A;
        }

        form {
            width: 350px;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            background-color: #E0C879;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
        }

        label {
            display: block;
            margin-bottom: 10px;
            font-weight: bold;
        }

        input[type="text"] {
            width: 100%;
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
            margin-bottom: 10px;
        }

        input[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 10px 16px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
        }

        input[type="submit"]:hover {
            background-color: #45a049;
        }

        input#id_purchase_date, 
        input#id_last_purchase_amount, 
        input#id_purchased_quantity {
            width: 100%;
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
            margin-bottom: 10px;
        }         
        
        
        select {
            padding: 8px;
            font-size: 16px; 
            border: 1px solid #ccc; 
            border-radius: 4px; 
            width: 100%; 
            box-sizing: border-box; 
        }
       
          
        input#id_purchase_date {
            width: 320px; 
        }

        form{
            max-width:322px;
            margin-bottom:100px;
        }

        input#id_last_purchase_amount {
            width: 311px;
        }

        input#id_purchased_quantity {
            width: 310px;
        }

        .alert-box {
            display: none;
            position: fixed;
            top: 50%; /* Center the box vertically */
            left: 50%; /* Center the box horizontally */
            transform: translate(-50%, -50%);
            background-color: #f44336;
            color: white;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            z-index: 1;
        }

        .back-btn {
            display: flex;
            justify-content: space-between;
            margin-top: 20px;
        }
        
        .back-btn button {
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
            width: 80px;
        }

        
        .back-btn button:hover {
          background-color: #45a049;  
        }
        

</style>

</html> 

myapp/templates/add_student.html
{% load static %}


<!DOCTYPE html>
<html>
<head>
    <title>Add Student</title>
</head>

<body>

    <form method="post" action="{% url 'add_student' %}">
        {% csrf_token %}
        <h1>Add Student</h1>
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" required>

        <label for="grade">Grade:</label>
        <input type="text" id="grade" name="grade" required>

        <label for="mail">Mail:</label>
        <input type="email" id="mail" name="mail" required>

        <label for="limit">Limit:</label>
        <input type="number" id="limit" name="limit" required>

        <div  class="back-btn">
         <button onclick="location.href='{% url 'student' %}'">Back</button>
          <input type="submit" value="Add Student">
        </div>
    </form>

    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            font-family: Arial, sans-serif;
            background-color: #E87461;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
            color: #FE910A;
        }

        form {
            width: 350px;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            background-color: #E0C879;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
        }

        label {
            display: block;
            margin-bottom: 10px;
        }

        input[type="text"],
        input[type="email"],
        input[type="number"] {
            width: 100%;
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
            margin-bottom: 10px;
        }

        input[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 10px 16px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
        }

        input[type="submit"]:hover {
            background-color: #45a049;
        }

        .back-btn {
            display: flex;
            justify-content: space-between;
            margin-top: 20px;
        }
        
        .back-btn button {
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
            width: 80px;
        }

        
        .back-btn button:hover {
          background-color: #45a049;  
        }
        
    </style>
</body>
</html>

myapp/templates/add_to_cart.html
{%  load static %}



 <!DOCTYPE html>
<html>
<head>
    <title>Add Purchase</title>
</head>

<body>
</head>
<body>
 


<form method="post" id="addToCartForm">
    <h1>Add Purchase</h1>
    {% csrf_token %}
    {{ form.as_p }}
   
    <div  class="back-btn">
     <button  onclick="location.href='{% url 'purchase' %}'"> Back
     </button>
      <button type="submit" name="action" value="add_to_cart">Add to Cart</button>
      <button onclick="location.href='{% url 'view_cart' %}'">View Cart</button>

    </div>
    
   
</form>
<div class="alert-box" id="popupMessage">
    <p>  {{ error_message }} </p>
</div> 
<div>
 </div>


<div id="totalAmountDisplay">
    {% if total_price %}
        <p>Total Price: {{ total_price }}</p>
        {% comment %} <script>
            setTimeout(function() {
                window.location.href = "{% url 'purchase' %}";
            }, 2000); // Redirect after 3 seconds (adjust the delay as needed)
        </script> {% endcomment %}
    {% endif %}
</div>
<script>
    const quantityInput = document.getElementById('id_purchased_quantity');
    const itemSelect = document.getElementById('id_item'); // Assuming the HTML id for the item select field is "id_item"
    const totalAmountDisplay = document.getElementById('totalAmountDisplay');

    function calculateTotalAmount() {
        const quantity = parseInt(quantityInput.value);
        const itemPrice = parseFloat(itemSelect.options[itemSelect.selectedIndex].getAttribute('data-price'));
        const totalAmount = isNaN(quantity) || isNaN(itemPrice) ? '' : (quantity * itemPrice).toFixed(2);
        totalAmountDisplay.innerHTML = totalAmount ? `<p>Total Price: ${totalAmount}</p>` : '';

    if (parseInt(quantity) <= 0 || parseFloat(lastPurchaseAmount) <= 0) {
        document.getElementById('error-message').innerText = 'Invalid quantity or last purchase amount.';
        document.getElementById('error-message').style.display = 'block';
    } else {
        document.getElementById('error-message').innerText = '';
        document.getElementById('error-message').style.display = 'none';

    }
}
function showAlert() {
    var popup = document.getElementById("popupMessage");
    popup.style.display = "block";
    var duration = 3000; // 5 seconds (adjust this value as needed)

    setTimeout(function() {
        popup.style.display = "none";
    }, duration);
}
window.onload = function() {
    var error_message = "{{ error_message }}";
    if (error_message) {
        showAlert();
    }
};
</script>

 
</body>
</html> 

 
<style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            background-color: #f1f1f1;
            padding: 20px;
            background-color: #E87461;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
            color: #FE910A;
        }

        form {
            width: 350px;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            background-color: #E0C879;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
        }

        label {
            display: block;
            margin-bottom: 10px;
            font-weight: bold;
        }

        input[type="text"] {
            width: 100%;
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
            margin-bottom: 10px;
        }

        input[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 10px 16px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
        }

        input[type="submit"]:hover {
            background-color: #45a049;
        }

        input#id_purchase_date, 
        input#id_last_purchase_amount, 
        input#id_purchased_quantity {
            width: 100%;
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
            margin-bottom: 10px;
        }         
        
        
        select {
            padding: 8px;
            font-size: 16px; 
            border: 1px solid #ccc; 
            border-radius: 4px; 
            width: 100%; 
            box-sizing: border-box; 
        }
       
          
        input#id_purchase_date {
            width: 320px; 
        }

        form{
            max-width:322px;
            margin-bottom:100px;
        }

        input#id_last_purchase_amount {
            width: 311px;
        }

        input#id_purchased_quantity {
            width: 310px;
        }

        .alert-box {
            display: none;
            position: fixed;
            top: 50%; /* Center the box vertically */
            left: 50%; /* Center the box horizontally */
            transform: translate(-50%, -50%);
            background-color: #f44336;
            color: white;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            z-index: 1;
        }

        .back-btn {
            display: flex;
            justify-content: space-between;
            margin-top: 20px;
        }
        
        .back-btn button {
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
            width: 80px;
        }

        
        .back-btn button:hover {
          background-color: #45a049;  
        }
        

</style>

</html> 